server:
  port: 8081

#nacos\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#\u6570\u636E\u5E93
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.243.178:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  redis:
    host: 47.98.243.178

mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  global-config:
    db-config:
      id-type: auto #\u9ED8\u8BA4\u4F7F\u7528\u6570\u636E\u5E93\u81EA\u589E